# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '//mnt/c/Users/Nawar/Documents/GitHub/OSRS-Combat/Code/osrsmath/apps/GUI/monsters/monsters_skeleton.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Monsters(object):
    def setupUi(self, Monsters):
        Monsters.setObjectName("Monsters")
        Monsters.resize(578, 451)
        self.gridLayout = QtWidgets.QGridLayout(Monsters)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Monsters)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(-1, 1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_2.addWidget(self.frame_2, 2, 6, 1, 1)
        self.custom_name = QtWidgets.QLineEdit(self.frame)
        self.custom_name.setObjectName("custom_name")
        self.gridLayout_2.addWidget(self.custom_name, 7, 2, 1, 3)
        self.search = QtWidgets.QComboBox(self.frame)
        self.search.setEditable(True)
        self.search.setObjectName("search")
        self.gridLayout_2.addWidget(self.search, 0, 2, 1, 3)
        self.image_3 = QtWidgets.QFrame(self.frame)
        self.image_3.setFrameShape(QtWidgets.QFrame.Box)
        self.image_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.image_3.setLineWidth(1)
        self.image_3.setObjectName("image_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.image_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.defensive_magic = QtWidgets.QLineEdit(self.image_3)
        self.defensive_magic.setObjectName("defensive_magic")
        self.gridLayout_5.addWidget(self.defensive_magic, 2, 5, 1, 1)
        self.defensive_stab = QtWidgets.QLineEdit(self.image_3)
        self.defensive_stab.setObjectName("defensive_stab")
        self.gridLayout_5.addWidget(self.defensive_stab, 2, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.image_3)
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap(":/monster/Ranged_icon.webp"))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 1, 6, 1, 1)
        self.defensive_slash = QtWidgets.QLineEdit(self.image_3)
        self.defensive_slash.setObjectName("defensive_slash")
        self.gridLayout_5.addWidget(self.defensive_slash, 2, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.image_3)
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/monster/White_scimitar.webp"))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 1, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.image_3)
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(":/monster/White_warhammer.webp"))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 1, 4, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.image_3)
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/monster/Magic_icon.webp"))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 1, 5, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.image_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setLineWidth(3)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_5.addWidget(self.frame_6, 0, 2, 1, 5)
        self.label_25 = QtWidgets.QLabel(self.image_3)
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap(":/monster/Defence_icon.webp"))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 1, 0, 1, 1)
        self.defensive_crush = QtWidgets.QLineEdit(self.image_3)
        self.defensive_crush.setObjectName("defensive_crush")
        self.gridLayout_5.addWidget(self.defensive_crush, 2, 4, 1, 1)
        self.defensive_ranged = QtWidgets.QLineEdit(self.image_3)
        self.defensive_ranged.setObjectName("defensive_ranged")
        self.gridLayout_5.addWidget(self.defensive_ranged, 2, 6, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.image_3)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/monster/White_dagger.webp"))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 1, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.image_3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 0, 1, 3, 1)
        self.label_26 = QtWidgets.QLabel(self.image_3)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.image_3, 5, 1, 1, 5)
        self.image = QtWidgets.QFrame(self.frame)
        self.image.setFrameShape(QtWidgets.QFrame.Box)
        self.image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.image.setLineWidth(1)
        self.image.setObjectName("image")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.image)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.strength = QtWidgets.QLineEdit(self.image)
        self.strength.setObjectName("strength")
        self.gridLayout_3.addWidget(self.strength, 3, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.image)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/monster/Magic_icon.webp"))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 6, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.image)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/monster/Hitpoints_icon.webp"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.image)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/monster/Ranged_icon.webp"))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 7, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.image)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 1, 1, 3, 1)
        self.magic = QtWidgets.QLineEdit(self.image)
        self.magic.setObjectName("magic")
        self.gridLayout_3.addWidget(self.magic, 3, 6, 1, 1)
        self.attack = QtWidgets.QLineEdit(self.image)
        self.attack.setObjectName("attack")
        self.gridLayout_3.addWidget(self.attack, 3, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.image)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/monster/Strength_icon.webp"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 4, 1, 1)
        self.defence = QtWidgets.QLineEdit(self.image)
        self.defence.setObjectName("defence")
        self.gridLayout_3.addWidget(self.defence, 3, 5, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.image)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_21 = QtWidgets.QLabel(self.frame_3)
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(":/monster/Combat_icon.webp"))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.image)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/monster/Defence_icon.webp"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 5, 1, 1)
        self.health = QtWidgets.QLineEdit(self.image)
        self.health.setObjectName("health")
        self.gridLayout_3.addWidget(self.health, 3, 2, 1, 1)
        self.ranged = QtWidgets.QLineEdit(self.image)
        self.ranged.setObjectName("ranged")
        self.gridLayout_3.addWidget(self.ranged, 3, 7, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.image)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/monster/Attack_icon.webp"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 3, 1, 1)
        self.combat_level = QtWidgets.QLineEdit(self.image)
        self.combat_level.setObjectName("combat_level")
        self.gridLayout_3.addWidget(self.combat_level, 3, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.image)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.image, 2, 1, 1, 5)
        self.image_2 = QtWidgets.QFrame(self.frame)
        self.image_2.setFrameShape(QtWidgets.QFrame.Box)
        self.image_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.image_2.setLineWidth(1)
        self.image_2.setObjectName("image_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.image_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.aggressive_attack = QtWidgets.QLineEdit(self.image_2)
        self.aggressive_attack.setObjectName("aggressive_attack")
        self.gridLayout_4.addWidget(self.aggressive_attack, 2, 2, 1, 1)
        self.aggressive_magic_damage = QtWidgets.QLineEdit(self.image_2)
        self.aggressive_magic_damage.setObjectName("aggressive_magic_damage")
        self.gridLayout_4.addWidget(self.aggressive_magic_damage, 2, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.image_2)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/monster/Strength_icon.webp"))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 1, 3, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.image_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 0, 1, 3, 1)
        self.frame_5 = QtWidgets.QFrame(self.image_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(3)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_4.addWidget(self.frame_5, 0, 2, 1, 6)
        self.label_23 = QtWidgets.QLabel(self.image_2)
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap(":/monster/Attack_icon.webp"))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 1, 0, 1, 1)
        self.aggressive_ranged = QtWidgets.QLineEdit(self.image_2)
        self.aggressive_ranged.setObjectName("aggressive_ranged")
        self.gridLayout_4.addWidget(self.aggressive_ranged, 2, 6, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.image_2)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/monster/Ranged_icon.webp"))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 6, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.image_2)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/monster/Magic_icon.webp"))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 4, 1, 1)
        self.aggressive_strength = QtWidgets.QLineEdit(self.image_2)
        self.aggressive_strength.setObjectName("aggressive_strength")
        self.gridLayout_4.addWidget(self.aggressive_strength, 2, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.image_2)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/monster/Attack_icon.webp"))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.image_2)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/monster/Magic_Damage_icon.webp"))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 5, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.image_2)
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/monster/Ranged_Strength_icon.webp"))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 7, 1, 1)
        self.aggressive_ranged_strength = QtWidgets.QLineEdit(self.image_2)
        self.aggressive_ranged_strength.setObjectName("aggressive_ranged_strength")
        self.gridLayout_4.addWidget(self.aggressive_ranged_strength, 2, 7, 1, 1)
        self.aggressive_magic = QtWidgets.QLineEdit(self.image_2)
        self.aggressive_magic.setObjectName("aggressive_magic")
        self.gridLayout_4.addWidget(self.aggressive_magic, 2, 4, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.image_2)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.image_2, 4, 1, 1, 5)
        self.nmz_only = QtWidgets.QCheckBox(self.frame)
        self.nmz_only.setObjectName("nmz_only")
        self.gridLayout_2.addWidget(self.nmz_only, 0, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 7, 1, 1, 1)
        self.add = QtWidgets.QPushButton(self.frame)
        self.add.setObjectName("add")
        self.gridLayout_2.addWidget(self.add, 7, 5, 1, 1)
        self.wiki_link = QtWidgets.QPushButton(self.frame)
        self.wiki_link.setObjectName("wiki_link")
        self.gridLayout_2.addWidget(self.wiki_link, 0, 5, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 6, 1, 1, 1)
        self.xp_per_hit = QtWidgets.QLineEdit(self.frame)
        self.xp_per_hit.setText("")
        self.xp_per_hit.setObjectName("xp_per_hit")
        self.gridLayout_2.addWidget(self.xp_per_hit, 6, 2, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Monsters)
        QtCore.QMetaObject.connectSlotsByName(Monsters)
        Monsters.setTabOrder(self.nmz_only, self.search)
        Monsters.setTabOrder(self.search, self.wiki_link)
        Monsters.setTabOrder(self.wiki_link, self.combat_level)
        Monsters.setTabOrder(self.combat_level, self.health)
        Monsters.setTabOrder(self.health, self.attack)
        Monsters.setTabOrder(self.attack, self.strength)
        Monsters.setTabOrder(self.strength, self.defence)
        Monsters.setTabOrder(self.defence, self.magic)
        Monsters.setTabOrder(self.magic, self.ranged)
        Monsters.setTabOrder(self.ranged, self.aggressive_attack)
        Monsters.setTabOrder(self.aggressive_attack, self.aggressive_strength)
        Monsters.setTabOrder(self.aggressive_strength, self.aggressive_magic)
        Monsters.setTabOrder(self.aggressive_magic, self.aggressive_magic_damage)
        Monsters.setTabOrder(self.aggressive_magic_damage, self.aggressive_ranged)
        Monsters.setTabOrder(self.aggressive_ranged, self.aggressive_ranged_strength)
        Monsters.setTabOrder(self.aggressive_ranged_strength, self.defensive_stab)
        Monsters.setTabOrder(self.defensive_stab, self.defensive_slash)
        Monsters.setTabOrder(self.defensive_slash, self.defensive_crush)
        Monsters.setTabOrder(self.defensive_crush, self.defensive_magic)
        Monsters.setTabOrder(self.defensive_magic, self.defensive_ranged)
        Monsters.setTabOrder(self.defensive_ranged, self.xp_per_hit)
        Monsters.setTabOrder(self.xp_per_hit, self.custom_name)
        Monsters.setTabOrder(self.custom_name, self.add)

    def retranslateUi(self, Monsters):
        _translate = QtCore.QCoreApplication.translate
        Monsters.setWindowTitle(_translate("Monsters", "Form"))
        self.label_26.setText(_translate("Monsters", " Defensive Stats "))
        self.label_22.setText(_translate("Monsters", "   Combat Stats  "))
        self.label_24.setText(_translate("Monsters", "Aggressive Stats"))
        self.nmz_only.setText(_translate("Monsters", "NMZ only"))
        self.label_27.setText(_translate("Monsters", "Custom Name"))
        self.add.setText(_translate("Monsters", "Add"))
        self.wiki_link.setText(_translate("Monsters", "See on Wiki"))
        self.label_20.setText(_translate("Monsters", "xp/damage"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Monsters = QtWidgets.QWidget()
    ui = Ui_Monsters()
    ui.setupUi(Monsters)
    Monsters.show()
    sys.exit(app.exec_())
