import osrsmath.apps.GUI.config as config

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '//mnt/c/Users/Nawar/Documents/GitHub/OSRS-Combat/Code/osrsmath/apps/optimize/optimize.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(714, 738)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ammo = QtWidgets.QComboBox(self.frame)
        self.ammo.setObjectName("ammo")
        self.gridLayout_2.addWidget(self.ammo, 5, 2, 1, 2)
        self.sheild = QtWidgets.QComboBox(self.frame)
        self.sheild.setObjectName("sheild")
        self.gridLayout_2.addWidget(self.sheild, 8, 2, 1, 2)
        self.ring = QtWidgets.QComboBox(self.frame)
        self.ring.setObjectName("ring")
        self.gridLayout_2.addWidget(self.ring, 11, 2, 1, 2)
        self.neck = QtWidgets.QComboBox(self.frame)
        self.neck.setObjectName("neck")
        self.gridLayout_2.addWidget(self.neck, 4, 2, 1, 2)
        self.weapon = QtWidgets.QComboBox(self.frame)
        self.weapon.setObjectName("weapon")
        self.gridLayout_2.addWidget(self.weapon, 6, 2, 1, 2)
        self.body = QtWidgets.QComboBox(self.frame)
        self.body.setObjectName("body")
        self.gridLayout_2.addWidget(self.body, 7, 2, 1, 2)
        self.head = QtWidgets.QComboBox(self.frame)
        self.head.setObjectName("head")
        self.gridLayout_2.addWidget(self.head, 1, 2, 1, 2)
        self.feet = QtWidgets.QComboBox(self.frame)
        self.feet.setObjectName("feet")
        self.gridLayout_2.addWidget(self.feet, 10, 2, 1, 2)
        self.cape = QtWidgets.QComboBox(self.frame)
        self.cape.setObjectName("cape")
        self.gridLayout_2.addWidget(self.cape, 3, 2, 1, 2)
        self.gloves = QtWidgets.QComboBox(self.frame)
        self.gloves.setObjectName("gloves")
        self.gridLayout_2.addWidget(self.gloves, 9, 2, 1, 2)
        self.cape_button = QtWidgets.QPushButton(self.frame)
        self.cape_button.setObjectName("cape_button")
        self.gridLayout_2.addWidget(self.cape_button, 3, 1, 1, 1)
        self.neck_button = QtWidgets.QPushButton(self.frame)
        self.neck_button.setObjectName("neck_button")
        self.gridLayout_2.addWidget(self.neck_button, 4, 1, 1, 1)
        self.ammo_button = QtWidgets.QPushButton(self.frame)
        self.ammo_button.setObjectName("ammo_button")
        self.gridLayout_2.addWidget(self.ammo_button, 5, 1, 1, 1)
        self.weapon_button = QtWidgets.QPushButton(self.frame)
        self.weapon_button.setObjectName("weapon_button")
        self.gridLayout_2.addWidget(self.weapon_button, 6, 1, 1, 1)
        self.body_button = QtWidgets.QPushButton(self.frame)
        self.body_button.setObjectName("body_button")
        self.gridLayout_2.addWidget(self.body_button, 7, 1, 1, 1)
        self.shield_button = QtWidgets.QPushButton(self.frame)
        self.shield_button.setObjectName("shield_button")
        self.gridLayout_2.addWidget(self.shield_button, 8, 1, 1, 1)
        self.gloves_button = QtWidgets.QPushButton(self.frame)
        self.gloves_button.setObjectName("gloves_button")
        self.gridLayout_2.addWidget(self.gloves_button, 9, 1, 1, 1)
        self.feet_button = QtWidgets.QPushButton(self.frame)
        self.feet_button.setObjectName("feet_button")
        self.gridLayout_2.addWidget(self.feet_button, 10, 1, 1, 1)
        self.ring_button = QtWidgets.QPushButton(self.frame)
        self.ring_button.setObjectName("ring_button")
        self.gridLayout_2.addWidget(self.ring_button, 11, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 12, 1, 1, 1)
        self.head_button = QtWidgets.QPushButton(self.frame)
        self.head_button.setObjectName("head_button")
        self.gridLayout_2.addWidget(self.head_button, 1, 1, 1, 1)
        self.xp_rate = QtWidgets.QLineEdit(self.frame)
        self.xp_rate.setReadOnly(True)
        self.xp_rate.setObjectName("xp_rate")
        self.gridLayout_2.addWidget(self.xp_rate, 12, 3, 1, 1)
        self.gridLayout.addWidget(self.frame, 6, 0, 2, 3)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout.addWidget(self.frame_2, 9, 0, 1, 1)
        self.training_skill = QtWidgets.QComboBox(Form)
        self.training_skill.setObjectName("training_skill")
        self.training_skill.addItem("")
        self.training_skill.addItem("")
        self.training_skill.addItem("")
        self.training_skill.addItem("")
        self.training_skill.addItem("")
        self.gridLayout.addWidget(self.training_skill, 5, 0, 1, 1)
        self.opponents = QtWidgets.QListWidget(Form)
        self.opponents.setObjectName("opponents")
        self.gridLayout.addWidget(self.opponents, 2, 0, 1, 5)
        self.evaluate = QtWidgets.QPushButton(Form)
        self.evaluate.setObjectName("evaluate")
        self.gridLayout.addWidget(self.evaluate, 5, 1, 1, 1)
        self.best_in_slot_bonuses = QtWidgets.QTableWidget(Form)
        self.best_in_slot_bonuses.setShowGrid(True)
        self.best_in_slot_bonuses.setObjectName("best_in_slot_bonuses")
        self.best_in_slot_bonuses.setColumnCount(1)
        self.best_in_slot_bonuses.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.best_in_slot_bonuses.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.best_in_slot_bonuses.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.best_in_slot_bonuses.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.best_in_slot_bonuses.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.best_in_slot_bonuses.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.best_in_slot_bonuses.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.best_in_slot_bonuses.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.best_in_slot_bonuses.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.best_in_slot_bonuses.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.best_in_slot_bonuses.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.best_in_slot_bonuses.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.best_in_slot_bonuses.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.best_in_slot_bonuses.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.best_in_slot_bonuses.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.best_in_slot_bonuses.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.best_in_slot_bonuses.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.best_in_slot_bonuses.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.best_in_slot_bonuses.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.best_in_slot_bonuses.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.best_in_slot_bonuses.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.best_in_slot_bonuses.setItem(9, 0, item)
        self.best_in_slot_bonuses.horizontalHeader().setStretchLastSection(True)
        self.best_in_slot_bonuses.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.best_in_slot_bonuses, 5, 4, 5, 1)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cape_button.setText(_translate("Form", "Cape"))
        self.neck_button.setText(_translate("Form", "Neck"))
        self.ammo_button.setText(_translate("Form", "Ammo"))
        self.weapon_button.setText(_translate("Form", "Weapon"))
        self.body_button.setText(_translate("Form", "Body"))
        self.shield_button.setText(_translate("Form", "Shield"))
        self.gloves_button.setText(_translate("Form", "Gloves"))
        self.feet_button.setText(_translate("Form", "Feet"))
        self.ring_button.setText(_translate("Form", "Ring"))
        self.label.setText(_translate("Form", "Xp/h"))
        self.head_button.setText(_translate("Form", "Head"))
        self.training_skill.setItemText(0, _translate("Form", "Train Attack"))
        self.training_skill.setItemText(1, _translate("Form", "Train Strength"))
        self.training_skill.setItemText(2, _translate("Form", "Train Defence"))
        self.training_skill.setItemText(3, _translate("Form", "Train Ranged"))
        self.training_skill.setItemText(4, _translate("Form", "Train Mage"))
        self.evaluate.setText(_translate("Form", "Evaluate!"))
        item = self.best_in_slot_bonuses.verticalHeaderItem(0)
        item.setText(_translate("Form", "Stab"))
        item = self.best_in_slot_bonuses.verticalHeaderItem(1)
        item.setText(_translate("Form", "Slash"))
        item = self.best_in_slot_bonuses.verticalHeaderItem(2)
        item.setText(_translate("Form", "Crush"))
        item = self.best_in_slot_bonuses.verticalHeaderItem(3)
        item.setText(_translate("Form", "Ranged"))
        item = self.best_in_slot_bonuses.verticalHeaderItem(4)
        item.setText(_translate("Form", "Magic"))
        item = self.best_in_slot_bonuses.verticalHeaderItem(5)
        item.setText(_translate("Form", "Melee Str"))
        item = self.best_in_slot_bonuses.verticalHeaderItem(6)
        item.setText(_translate("Form", "Ranged Str"))
        item = self.best_in_slot_bonuses.verticalHeaderItem(7)
        item.setText(_translate("Form", "Magic Str"))
        item = self.best_in_slot_bonuses.verticalHeaderItem(8)
        item.setText(_translate("Form", "Attack Speed"))
        item = self.best_in_slot_bonuses.verticalHeaderItem(9)
        item.setText(_translate("Form", "Cost"))
        item = self.best_in_slot_bonuses.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Bonuses"))
        __sortingEnabled = self.best_in_slot_bonuses.isSortingEnabled()
        self.best_in_slot_bonuses.setSortingEnabled(False)
        self.best_in_slot_bonuses.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
